ALTER TABLE characters
    CHANGE COLUMN strength might SMALLINT UNSIGNED NOT NULL DEFAULT 1,
    CHANGE COLUMN dexterity finesse SMALLINT UNSIGNED NOT NULL DEFAULT 1,
    CHANGE COLUMN intelligence intellect SMALLINT UNSIGNED NOT NULL DEFAULT 1,
    CHANGE COLUMN luck spirit SMALLINT UNSIGNED NOT NULL DEFAULT 1,
    CHANGE COLUMN status_points attribute_points INT UNSIGNED NOT NULL DEFAULT 0;
